### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by Samuel-Martineau** [Doudou8/EyeRest#2]
Is there a download link for the compiled app. I don't want to do it myself. Maybe use Github Actions to automate the process. That would allow you to use electron auto update.

Sincerely,

Samuel Martineau

PS. It would be nice to see screenshots of the app in the readme

**Comment by dkchiem** [comment]
You can now follow the instruction in the [Installation](https://github.com/Doudou8/EyeRest#installation) section to download the app. Unfortunately, because the app verification process is quite complex and expensive, the app can't have automatic updating. You will have to redownload the app if there is a new release. I also added screenshots to the [README.md](https://github.com/Doudou8/EyeRest/blob/master/README.md).
